
.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - quality
  - deploy
  - merge
  - release

build_snapshot:
  stage: build
  <<: *default
  <<: *default_tag
  when: manual
  script:
    - mvn clean package -U -DskipTests=true

merge_ready:
  stage: quality
  <<: *default
  <<: *default_tag
  when: manual
  allow_failure: false
  script:
    - mvn verify -U -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

deploy_snapshot:
  stage: build
  <<: *default_tag
  <<: *default
  allow_failure: false
  script:
    - mvn deploy -U -DskipTests=true
  when: manual

release:
  <<: *default_tag
  stage: release
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull origin master
    - git checkout develop
    - git pull origin develop
    - mvn -U -DgenerateChangelog jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop
