.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - deploy
  - quality
  - merge
  - release

Build Package:
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - echo $HTTP_PROXY
    - echo $HTTPS_PROXY
    - mvn -Dhttp.proxyHost=tinyproxy -Dhttp.proxyPort=8888 -Dhttps.proxyHost=tinyproxy -Dhttps.proxyPort=8888 clean package -U
  except:
    - master
    - develop
  artifacts:
    paths:
      - "*/target"
    expire_in: "10 mins"

Deploy Snapshot:
  stage: deploy
  <<: *default_tag
  <<: *default
  script:
    - echo $HTTP_PROXY
    - echo $HTTPS_PROXY
    - mvn -Dhttp.proxyHost=tinyproxy -Dhttp.proxyPort=8888 -Dhttps.proxyHost=tinyproxy -Dhttps.proxyPort=8888 deploy -DskipTests=true
